import { Project } from './type';

export const PROJECTS: Project[] = [
  {
    id: 1,
    title: '메이드존',
    skills: ['Next.js', 'TypeScript', 'TailwindCSS', 'Framer Motion'],
    period: '2025.10 ~ 2025.12',
    description:
      '체계적인 학습 관리 시스템과 전문 멘토링으로 학생들의 자기주도학습을 지원하는 프리미엄 독서실',
    thumbnail: 'madezone/madezone',
    desktopImages: [
      'madezone/madezone',
      'madezone/madezone-1',
      'madezone/madezone-2',
      'madezone/madezone-3',
      'madezone/madezone-4',
    ],
    company: '엠유소프트',
    contribution: '프론트엔드(70%)',
    role: 'Figma 기반 디자인 화면 구현, API 연동, 재사용 가능한 공통 컴포넌트 아키텍처 설계',
    members: 'FE 1명, BE 1명, Design 1명',
    url: 'https://madezone.madeedu.co.kr/',
    details: [
      '메이드존 교육 그룹의 통합 웹 서비스 - 메인 홈페이지, 입시 컨설팅, 브랜드별 교육 서비스 프론트엔드 개발자로 프로젝트에 참여',
      'Next.js 의 middleware를 활용하여 멀티 도메인 브랜딩 시스템 (도메인별 브랜드 자동 감지) 개발',
      'API 명세에 맞는 요청을 구현하고, 에러 상황에 따른 사용자 피드백 처리 로직을 구성',
      '동적 SEO 메타데이터 생성으로 인해 구글 검색 페이지 최상단 노출',
      'Framer Motion을 사용하여 페이지 애니메이션 구현',
      '커스텀 디자인 시스템 (타이포그래피, 컬러 팔레트)을 활용하여 개발속도 20% 향상',
      '반응형 웹 디자인 구현',
    ],
  },
  {
    id: 2,
    title: '루나폴',
    skills: ['React', 'Vite', 'TypeScript', 'TailwindCSS', 'React-i18next'],
    period: '2025.10 ~ 2025.11',
    description:
      'AI 음성 내레이션으로 공간의 세계관을 따라 걷듯 체험하게 하는 몰입형 오디오 가이드 서비스',
    thumbnail: 'lunafall/lunafall',
    mobileImages: [
      'lunafall/lunafall',
      'lunafall/lunafall-1',
      'lunafall/lunafall-2',
      'lunafall/lunafall-3',
      'lunafall/lunafall-4',
    ],
    company: '엠유소프트',
    contribution: '프론트엔드(80%)',
    role: 'Figma 기반 디자인 화면 구현, API 연동, 재사용 가능한 공통 컴포넌트 아키텍처 설계',
    members: 'FE 1명, BE 1명, Design 1명',
    url: 'https://guide.lunafall.co.kr/',
    details: [
      '루나폴 다국어 지원 관광 가이드 웹 애플리케이션 개발자로 프로젝트에 참여',
      'react-i18next를 활용하여 한국어/중국어/영어 지원 시스템 구축',
      'API 명세에 맞는 요청을 구현하고, 에러 상황에 따른 사용자 피드백 처리 로직을 구성',
      '모바일 퍼스트로 웹 애플리케이션으로 UI/UX 구현',
    ],
  },
  {
    id: 3,
    title: '당재재',
    skills: [
      'Next.js',
      'TypeScript',
      'TailwindCSS',
      'Zustand',
      'React-hook-form',
      'Zod',
    ],
    period: '2025.11 ~ 2025.12',
    description:
      '체계적인 학습 관리 시스템과 전문 멘토링으로 학생들의 자기주도학습을 지원하는 프리미엄 독서실',
    thumbnail: 'dangjaejae/dangjaejae',
    desktopImages: [
      'dangjaejae/dangjaejae',
      'dangjaejae/dangjaejae-1',
      'dangjaejae/dangjaejae-2',
      'dangjaejae/dangjaejae-3',
    ],
    company: '엠유소프트',
    contribution: '프론트엔드(90%)',
    role: 'Figma 기반 디자인 화면 구현, API 연동, 재사용 가능한 공통 컴포넌트 아키텍처 설계',
    members: 'FE 1명, BE 1명',
    url: 'https://www.jaejaeinfo.com/',
    details: [
      '부동산 재개발, 재건축 정보 플랫폼 프론트엔드 개발자로 프로젝트에 참여',
      'Zustand 기반 필터링, 사업지 비교 등 상태관리 시스템 구축',
      'API 명세에 맞는 요청을 구현하고, 에러 상황에 따른 사용자 피드백 처리 로직을 구성',
      '가격/ 지역/ 사업단계 등 다중 필터링 및 범위 검색 시스템 구현',
      '카카오 맵 API 연동으로 재개발, 재건축 지역 시각화',
      '사용자 상태에 따라 다른 UX를 제공하는 비즈니스 로직 설계',
      '카카오 OAuth 2.0 기반 소셜 로그인 기능 구현',
      '사업지 비교 그래프로 시각화',
      '반응형 웹 디자인 구현',
    ],
  },
  {
    id: 4,
    title: 'Uuno',
    skills: [
      'Next.js',
      'TypeScript',
      'TailwindCSS',
      'Zustand',
      'React-hook-form',
      'Zod',
      'Konva.js',
      'Supabase',
    ],
    period: '2025.04 ~ 2025.06',
    description:
      '인터랙티브한 디지털 명함을 쉽게 제작하고 공유할 수 있는 웹 플랫폼',
    thumbnail: 'uuno/uuno',
    desktopImages: [
      'uuno/uuno',
      'uuno/uuno-1',
      'uuno/uuno-2',
      'uuno/uuno-3',
      'uuno/uuno-4',
    ],
    company: '팀 프로젝트',
    contribution: '프론트엔드(40%)',
    role: 'Figma 기반 디자인 화면 구현, "Kakao, Google OAuth 2.0 기반 소셜 로그인 기능 구현, Konva.js를 활용한 명함 커스터마이징 기능 개발',
    members: 'FE 4명, Design 2명',
    url: 'https://www.uuno.kr/',
    github: 'https://github.com/K-jisu/uuno/tree/main',
    notion:
      'https://chalk-cerise-6ec.notion.site/Uuno-You-Uno-1c9d8e847058809e8837df39a6c23989?source=copy_link',
    details: [
      'Kakao, Google OAuth 2.0 기반 소셜 로그인 기능 구현',
      'React-hook-form과 Zod를 활용한 사용자 입력 검증 시스템 구축',
      'Konva.js를 활용하여 도형 추가 및 편집, 명함 커스터마이징 기능 개발',
      'Zustand를 활용하여 명함 편집 상태 관리 시스템 구축',
      'https://chalk-cerise-6ec.notion.site/Undo-Redo-1d8d8e84705880f9bc9add5f2beb0eab, Undo/Redo 기능구현에 대한 고민에 관한 글',
      '팀원 4명과 도형/텍스트 추가, 위치 이동, 레이어 변경 등 10가지 이상의 핵심 편집 시나리오를 반복 검증해 오류 0건을 확인',
      '사용자 20명 대상 사용성 평가에서 Undo/Redo 기능에 대한 긍정적 피드백을 확보했고, 기능 오류 보고는 없었음',

      '에디터 레이아웃 및 인터랙션 구현',
      '캔버스의 그려진 요소를 이용하여 명함 미리보기 기능 구현',
    ],
  },
];
